/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System_GUI;

import Java_class.Bag_Details;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;


public class Add_Bag extends javax.swing.JFrame {

    /**
     * Creates new form Add_Bag
     */
    public Add_Bag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGender = new javax.swing.JPanel();
        txtAddEmployee = new javax.swing.JLabel();
        txtEmp_Name = new javax.swing.JLabel();
        txtEmp_Id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEPF = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cmbColor = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        add_employee = new javax.swing.JButton();
        btnPervious = new javax.swing.JButton();
        txtDOB = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGender.setBackground(new java.awt.Color(255, 255, 153));

        txtAddEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAddEmployee.setForeground(new java.awt.Color(0, 0, 204));
        txtAddEmployee.setText("Add Bag Details");

        txtEmp_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmp_Name.setText("Bag Name");

        txtEmp_Id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmp_Id.setText("Bag Id");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Bag Color");

        txtEPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEPF.setText("Bag Code");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtDepartment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDepartment.setText("Catagorise");

        txtDesignation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDesignation.setText("Price");

        cmbColor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Blue", "Yellow", "Brown" }));

        add_employee.setBackground(new java.awt.Color(153, 255, 102));
        add_employee.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        add_employee.setText("Add");
        add_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employeeActionPerformed(evt);
            }
        });

        btnPervious.setBackground(new java.awt.Color(255, 204, 255));
        btnPervious.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPervious.setText("Pervoius");
        btnPervious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerviousActionPerformed(evt);
            }
        });

        txtDOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDOB.setText("Bag Size");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtGenderLayout = new javax.swing.GroupLayout(txtGender);
        txtGender.setLayout(txtGenderLayout);
        txtGenderLayout.setHorizontalGroup(
            txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtGenderLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(txtAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(txtGenderLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmp_Id)
                        .addComponent(jLabel4)
                        .addComponent(txtEPF)
                        .addComponent(txtDOB)
                        .addComponent(txtEmp_Name)
                        .addComponent(txtDepartment)
                        .addComponent(txtDesignation)
                        .addComponent(txtAddress))
                    .addComponent(btnPervious))
                .addGap(82, 82, 82)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addGroup(txtGenderLayout.createSequentialGroup()
                        .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(txtGenderLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(add_employee)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtGenderLayout.setVerticalGroup(
            txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtGenderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtAddEmployee)
                .addGap(29, 29, 29)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmp_Name)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtGenderLayout.createSequentialGroup()
                        .addComponent(txtEmp_Id)
                        .addGap(18, 18, 18)
                        .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEPF))
                .addGap(18, 18, 18)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDOB)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartment)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(txtAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesignation)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(txtGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPervious, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employeeActionPerformed
        if (
            jTextField1.getText().isEmpty() ||
            jTextField2.getText().isEmpty() ||
            cmbColor.getSelectedItem().toString().isEmpty() ||
            jTextField3.getText().isEmpty() ||
            jTextField4.getText().isEmpty() ||
            jTextField5.getText().isEmpty()||
             jTextField6.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fileds cannot be empty" ,
                "Add a new Bag", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String BagName = jTextField1.getText();
            String BagId = jTextField2.getText();
            String BagColor = cmbColor.getSelectedItem().toString();
            String BagCode = jTextField3.getText();
            String Catagorise = jTextField6.getText();
            String BagSize = jTextField4.getText();
            String Price = jTextField5.getText();
         
           Bag_Details newBa = new Bag_Details(BagName,BagId,BagColor,BagCode,BagSize, Catagorise,Price);

            boolean success = newBa.addBag();

            if (success) {
                try (FileWriter writer = new FileWriter("Bag.txt", true)) {
                    writer.write("Bag Code = " + BagCode + System.getProperty("line.separator"));
                    writer.write("Bag Name = " + BagName + System.getProperty("line.separator"));
                    writer.write(" Bag Size = " + BagSize + System.getProperty("line.separator"));
                    writer.write("Bag Id  = " + BagId + System.getProperty("line.separator"));
                    writer.write(" Bag Color = " + BagColor + System.getProperty("line.separator"));
                    writer.write("Price = " + Price + System.getProperty("line.separator"));
                    writer.write("Catagorise = " + Catagorise + System.getProperty("line.separator"));
                    writer.write("------------------------------------------" + System.getProperty("line.separator"));
                } catch (IOException e) {
                }

                JOptionPane.showMessageDialog(null,"Bag Added successfully" ,
                    "Add a new Bag", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null,"Sorry! Something went wrong with the application"
                    ,"Add a new Bag", JOptionPane.WARNING_MESSAGE);
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this,"Go Cashier Dashboard");

       Cashier_Dashboard D1= new Cashier_Dashboard ();
        D1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_employeeActionPerformed

    private void btnPerviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerviousActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Go  Cashier Dashboard");
        Cashier_Dashboard M1= new Cashier_Dashboard();
        M1.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnPerviousActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Bag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Bag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Bag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Bag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Bag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employee;
    private javax.swing.JButton btnPervious;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel txtAddEmployee;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtDOB;
    private javax.swing.JLabel txtDepartment;
    private javax.swing.JLabel txtDesignation;
    private javax.swing.JLabel txtEPF;
    private javax.swing.JLabel txtEmp_Id;
    private javax.swing.JLabel txtEmp_Name;
    private javax.swing.JPanel txtGender;
    // End of variables declaration//GEN-END:variables
}
