/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System_GUI;


public class Cashier_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Manager_Dashboard
     */
    public Cashier_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtManagerDashboard = new javax.swing.JLabel();
        btnAdd_Bag = new javax.swing.JButton();
        btnSearch_Bag = new javax.swing.JButton();
        btnAdd_catagorise = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtView_all_Bags = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtManagerDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtManagerDashboard.setForeground(new java.awt.Color(0, 51, 255));
        txtManagerDashboard.setText("Cashier Dashboard");

        btnAdd_Bag.setBackground(new java.awt.Color(153, 255, 255));
        btnAdd_Bag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd_Bag.setText("Add Bag");
        btnAdd_Bag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_BagActionPerformed(evt);
            }
        });

        btnSearch_Bag.setBackground(new java.awt.Color(153, 255, 204));
        btnSearch_Bag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch_Bag.setText("Search Bag");
        btnSearch_Bag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_BagActionPerformed(evt);
            }
        });

        btnAdd_catagorise.setBackground(new java.awt.Color(102, 255, 204));
        btnAdd_catagorise.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd_catagorise.setText("Add Categories");
        btnAdd_catagorise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_catagoriseActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 204));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtView_all_Bags.setBackground(new java.awt.Color(102, 255, 102));
        txtView_all_Bags.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtView_all_Bags.setText("View Bags");
        txtView_all_Bags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtView_all_BagsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch_Bag)
                            .addComponent(btnAdd_Bag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd_catagorise)
                            .addComponent(txtView_all_Bags))))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(txtManagerDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtManagerDashboard)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd_catagorise))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnAdd_Bag)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch_Bag)
                    .addComponent(txtView_all_Bags))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_BagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_BagActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Go Add Bag");
        Add_Bag A1= new Add_Bag();
        A1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdd_BagActionPerformed

    private void btnSearch_BagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_BagActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Go Search Bag Details");
        Search_Bag_Details S1= new Search_Bag_Details();
        S1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearch_BagActionPerformed

    private void btnAdd_catagoriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_catagoriseActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Go Add Categories Dashboard");
        Add_Catagorise D1= new Add_Catagorise ();
        D1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdd_catagoriseActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Go Login Screen");
        Login_Screen L1= new Login_Screen();
        L1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtView_all_BagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtView_all_BagsActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this,"Go View all bags");
        View_all_Bags A1= new  View_all_Bags();
        A1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtView_all_BagsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_Bag;
    private javax.swing.JButton btnAdd_catagorise;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch_Bag;
    private javax.swing.JLabel txtManagerDashboard;
    private javax.swing.JButton txtView_all_Bags;
    // End of variables declaration//GEN-END:variables
}
